import neonFrag from "./shaders/neon_isoclines.frag?raw";
import tanhFrag from "./shaders/terrain_tanh_isoclines.frag?raw";
import tunnelFrag from "./shaders/brownian_loop_tunnel.frag?raw";
import kochFrag from "./shaders/koch_snowflake.frag?raw";
import quasiFrag from "./shaders/quasi_snowflake.frag?raw";
import diffChromaticFrag from "./shaders/diffusion_chromatic_flow.frag?raw";
import diffEdgeFlowFrag from "./shaders/diffusion_edge_flow.frag?raw";
import diffThresholdFrag from "./shaders/diffusion_threshold_feedback.frag?raw";
import prismFrag from "./shaders/prismatic_fold_raymarch.frag?raw";
import seascapeFrag from "./shaders/seascape_tdm.frag?raw";
import tileableWaterPlusFrag from "./shaders/tileable_water_plus.frag?raw";
import sunsetPlusFrag from "./shaders/sunset_plus.frag?raw";
import zippyZapsFrag from "./shaders/zippy_zaps.frag?raw";
import spaceLightningPlusFrag from "./shaders/space_lightning_plus.frag?raw";
import lightningBladePlusFrag from "./shaders/lightning_blade_plus.frag?raw";
import mandelbulbInsidePlusFrag from "./shaders/mandelbulb_inside_plus.frag?raw";
import aurorasPlusFrag from "./shaders/auroras_plus.frag?raw";

export type KeyBinding = {
  inc: string;
  dec: string;
  step: number;
  shiftStep?: number;
};

export type ParamType = "float" | "int" | "seed";

export type ParamSpec = {
  id: string;
  label: string;
  uniform: string;
  type: ParamType;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  key?: KeyBinding;
  component?: 0 | 1 | 2;
};

export type AnimationConfig = {
  id: string;
  name: string;
  description: string;
  fragment: string;
  resolutionUniform: string;
  timeUniform: string;
  timeMode: "phase" | "seconds" | "looped";
  loopDuration?: number;
  loopUniform?: string;
  params: ParamSpec[];
  stateful?: boolean;
  bufferSize?: number;
  passUniform?: string;
  stateUniform?: string;
  gridUniform?: string;
};

export const animations: AnimationConfig[] = [
  {
    id: "neon",
    name: "Neon Isoclines",
    description: "Electric contour bands driven by seeded radial harmonics.",
    fragment: neonFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uPhase",
    timeMode: "phase",
    loopDuration: 8,
    params: [
      {
        id: "components",
        label: "Components",
        uniform: "uComponents",
        type: "int",
        value: 64,
        min: 1,
        max: 64,
        step: 1,
        key: { inc: "q", dec: "a", step: 1, shiftStep: 10 },
      },
      {
        id: "isoBands",
        label: "Iso Bands",
        uniform: "uIsoBands",
        type: "int",
        value: 8,
        min: 1,
        max: 64,
        step: 1,
        key: { inc: "w", dec: "s", step: 1, shiftStep: 10 },
      },
      {
        id: "lineThickness",
        label: "Line Thickness",
        uniform: "uLineThickness",
        type: "float",
        value: 0.25,
        min: 0.01,
        max: 0.75,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.02, shiftStep: 0.05 },
      },
      {
        id: "noiseAmount",
        label: "Noise Amount",
        uniform: "uNoiseAmount",
        type: "float",
        value: 2.5,
        min: 0,
        max: 5,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.1, shiftStep: 0.25 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "tanh-terrain",
    name: "Tanh Terrain Isoclines",
    description: "Tanh warped contours with bubbling noise and topo glow.",
    fragment: tanhFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uPhase",
    timeMode: "phase",
    loopDuration: 8,
    params: [
      {
        id: "scale",
        label: "Scale",
        uniform: "uScale",
        type: "float",
        value: 2.1,
        min: 0.1,
        max: 6,
        step: 0.05,
        key: { inc: "1", dec: "2", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "octaves",
        label: "Octaves",
        uniform: "uOctaves",
        type: "int",
        value: 4,
        min: 1,
        max: 12,
        step: 1,
        key: { inc: "3", dec: "4", step: 1 },
      },
      {
        id: "lacunarity",
        label: "Lacunarity",
        uniform: "uLacunarity",
        type: "float",
        value: 1.4,
        min: 1.01,
        max: 3,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.05, shiftStep: 0.15 },
      },
      {
        id: "gain",
        label: "Gain",
        uniform: "uGain",
        type: "float",
        value: 0.5,
        min: 0.01,
        max: 0.99,
        step: 0.01,
        key: { inc: "7", dec: "8", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "isoBands",
        label: "Iso Bands",
        uniform: "uIsoBands",
        type: "int",
        value: 16,
        min: 1,
        max: 96,
        step: 1,
        key: { inc: "q", dec: "a", step: 4, shiftStep: 12 },
      },
      {
        id: "lineThickness",
        label: "Line Thickness",
        uniform: "uLineThickness",
        type: "float",
        value: 0.2,
        min: 0.02,
        max: 0.75,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.02, shiftStep: 0.06 },
      },
      {
        id: "bubbleAmp",
        label: "Bubble Amp",
        uniform: "uBubbleAmp",
        type: "float",
        value: 0.26,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "bubbleFreq",
        label: "Bubble Freq",
        uniform: "uBubbleFreq",
        type: "float",
        value: 2.0,
        min: 0,
        max: 6,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.25, shiftStep: 0.75 },
      },
      {
        id: "bubbleDetail",
        label: "Bubble Detail",
        uniform: "uBubbleDetail",
        type: "float",
        value: 1.2,
        min: 0.1,
        max: 3,
        step: 0.05,
        key: { inc: "t", dec: "g", step: 0.1, shiftStep: 0.3 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "tunnel",
    name: "Brownian Loop Tunnel",
    description: "Looped tunnel with Brownian noise, fog, and hue spin.",
    fragment: tunnelFrag,
    resolutionUniform: "iResolution",
    timeUniform: "iTime",
    timeMode: "looped",
    loopDuration: 8,
    loopUniform: "uLoopDuration",
    params: [
      {
        id: "speed",
        label: "Speed",
        uniform: "uSpeed",
        type: "float",
        value: 1.0,
        min: 0.1,
        max: 4,
        step: 0.05,
        key: { inc: "1", dec: "2", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "twist",
        label: "Twist",
        uniform: "uTwist",
        type: "float",
        value: 4.0,
        min: 0,
        max: 10,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "noiseScale",
        label: "Noise Scale",
        uniform: "uNoiseScale",
        type: "float",
        value: 1.9,
        min: 0.1,
        max: 4,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "noiseAmp",
        label: "Noise Amp",
        uniform: "uNoiseAmp",
        type: "float",
        value: 0.5,
        min: 0,
        max: 2,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "colorCycle",
        label: "Color Cycle",
        uniform: "uColorCycle",
        type: "float",
        value: 1.0,
        min: 0,
        max: 4,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "fogDensity",
        label: "Fog Density",
        uniform: "uFogDensity",
        type: "float",
        value: 2.0,
        min: 0.1,
        max: 6,
        step: 0.05,
        key: { inc: "w", dec: "s", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "baseRed",
        label: "Base Red",
        uniform: "uBaseColor",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.05 },
        component: 0,
      },
      {
        id: "baseGreen",
        label: "Base Green",
        uniform: "uBaseColor",
        type: "float",
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.05 },
        component: 1,
      },
      {
        id: "baseBlue",
        label: "Base Blue",
        uniform: "uBaseColor",
        type: "float",
        value: 0.9,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.05 },
        component: 2,
      },
    ],
  },
  {
    id: "prismatic-fold",
    name: "Prismatic Fold Raymarch",
    description: "Rotating folded planes with prismatic glow and controllable depth.",
    fragment: prismFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "iterations",
        label: "Iterations",
        uniform: "uIterations",
        type: "int",
        value: 8,
        min: 1,
        max: 24,
        step: 1,
        key: { inc: "1", dec: "2", step: 1, shiftStep: 4 },
      },
      {
        id: "rotateSpeed",
        label: "Rotate Speed",
        uniform: "uRotateSpeed",
        type: "float",
        value: 0.2,
        min: -1.5,
        max: 1.5,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "foldOffset",
        label: "Fold Offset",
        uniform: "uFoldOffset",
        type: "float",
        value: 0.5,
        min: 0.1,
        max: 1.0,
        step: 0.01,
        key: { inc: "5", dec: "6", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "stepScale",
        label: "Step Scale",
        uniform: "uStepScale",
        type: "float",
        value: 5.0,
        min: 1.5,
        max: 10.0,
        step: 0.1,
        key: { inc: "7", dec: "8", step: 0.2, shiftStep: 0.6 },
      },
      {
        id: "glow",
        label: "Glow",
        uniform: "uGlow",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 3.0,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "cameraDistance",
        label: "Camera Distance",
        uniform: "uCameraDistance",
        type: "float",
        value: 50.0,
        min: 10.0,
        max: 120.0,
        step: 1.0,
        key: { inc: "w", dec: "s", step: 1.0, shiftStep: 5.0 },
      },
      {
        id: "cameraSpin",
        label: "Camera Spin",
        uniform: "uCameraSpin",
        type: "float",
        value: 1.0,
        min: -3.0,
        max: 3.0,
        step: 0.05,
        key: { inc: "e", dec: "d", step: 0.1, shiftStep: 0.4 },
      },
      {
        id: "colorMix",
        label: "Color Mix",
        uniform: "uColorMix",
        type: "float",
        value: 0.35,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "alphaGain",
        label: "Alpha Gain",
        uniform: "uAlphaGain",
        type: "float",
        value: 1.0,
        min: 0.3,
        max: 2.0,
        step: 0.05,
        key: { inc: "t", dec: "g", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "primRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.05 },
        component: 0,
      },
      {
        id: "primGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.7,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "u", dec: "j", step: 0.05 },
        component: 1,
      },
      {
        id: "primBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.9,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "i", dec: "k", step: 0.05 },
        component: 2,
      },
      {
        id: "secRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "o", dec: "l", step: 0.05 },
        component: 0,
      },
      {
        id: "secGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "p", dec: ";", step: 0.05 },
        component: 1,
      },
      {
        id: "secBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "[", dec: "]", step: 0.05 },
        component: 2,
      },
    ],
  },
  {
    id: "koch",
    name: "Koch Snowflake",
    description: "Iterative snowflake edges with neon glow mixing.",
    fragment: kochFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "iterations",
        label: "Iterations",
        uniform: "uIterations",
        type: "int",
        value: 4,
        min: 1,
        max: 8,
        step: 1,
        key: { inc: "1", dec: "2", step: 1 },
      },
      {
        id: "scale",
        label: "Scale",
        uniform: "uScale",
        type: "float",
        value: 0.8,
        min: 0.1,
        max: 2,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "rotation",
        label: "Rotation",
        uniform: "uRotation",
        type: "float",
        value: 0.2,
        min: -3,
        max: 3,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "glowIntensity",
        label: "Glow",
        uniform: "uGlowIntensity",
        type: "float",
        value: 2.0,
        min: 0,
        max: 5,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "primRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "q", dec: "a", step: 0.05 },
        component: 0,
      },
      {
        id: "primGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.6,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.05 },
        component: 1,
      },
      {
        id: "primBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.05 },
        component: 2,
      },
      {
        id: "secRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.05 },
        component: 0,
      },
      {
        id: "secGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.3,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.05 },
        component: 1,
      },
      {
        id: "secBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.6,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.05 },
        component: 2,
      },
    ],
  },
  {
    id: "quasi",
    name: "Quasi Snowflake",
    description: "Quasicrystal warp with a drifting snowflake outline.",
    fragment: quasiFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "iterations",
        label: "Iterations",
        uniform: "uIterations",
        type: "int",
        value: 6,
        min: 1,
        max: 8,
        step: 1,
        key: { inc: "1", dec: "2", step: 1 },
      },
      {
        id: "scale",
        label: "Scale",
        uniform: "uScale",
        type: "float",
        value: 1.1,
        min: 0.1,
        max: 3,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "rotation",
        label: "Rotation",
        uniform: "uRotation",
        type: "float",
        value: 0.0,
        min: -3,
        max: 3,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "glowIntensity",
        label: "Glow",
        uniform: "uGlowIntensity",
        type: "float",
        value: 0.9,
        min: 0,
        max: 3,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "primRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "q", dec: "a", step: 0.05 },
        component: 0,
      },
      {
        id: "primGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.8,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.05 },
        component: 1,
      },
      {
        id: "primBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.05 },
        component: 2,
      },
      {
        id: "secRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.02,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.02 },
        component: 0,
      },
      {
        id: "secGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.03,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.02 },
        component: 1,
      },
      {
        id: "secBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.05,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.02 },
        component: 2,
      },
    ],
  },
  {
    id: "tileable-water-plus",
    name: "Tileable Water Plus",
    description: "Tileable water ripples with tunable speed, scale, and tint.",
    fragment: tileableWaterPlusFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 2.0,
        step: 0.02,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "tileScale",
        label: "Tile Scale",
        uniform: "uTileScale",
        type: "float",
        value: 1.0,
        min: 0.5,
        max: 3.0,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "intensity",
        label: "Intensity",
        uniform: "uIntensity",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 2.5,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "contrast",
        label: "Contrast",
        uniform: "uContrast",
        type: "float",
        value: 1.2,
        min: 0.3,
        max: 2.5,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "waveShift",
        label: "Wave Shift",
        uniform: "uWaveShift",
        type: "float",
        value: 0.0,
        min: -3.0,
        max: 3.0,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "tintRed",
        label: "Tint Red",
        uniform: "uTint",
        type: "float",
        value: 0.0,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.02 },
        component: 0,
      },
      {
        id: "tintGreen",
        label: "Tint Green",
        uniform: "uTint",
        type: "float",
        value: 0.35,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.02 },
        component: 1,
      },
      {
        id: "tintBlue",
        label: "Tint Blue",
        uniform: "uTint",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.02 },
        component: 2,
      },
    ],
  },
  {
    id: "seascape",
    name: "Seascape Plus",
    description: "Raymarched ocean with tunable swell and camera drift.",
    fragment: seascapeFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 0.3,
        min: 0.0,
        max: 1.5,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "seaHeight",
        label: "Sea Height",
        uniform: "uSeaHeight",
        type: "float",
        value: 0.6,
        min: 0.1,
        max: 1.5,
        step: 0.02,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "seaChoppy",
        label: "Sea Choppy",
        uniform: "uSeaChoppy",
        type: "float",
        value: 4.0,
        min: 1.0,
        max: 7.0,
        step: 0.1,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.4 },
      },
      {
        id: "seaFreq",
        label: "Sea Freq",
        uniform: "uSeaFreq",
        type: "float",
        value: 0.16,
        min: 0.05,
        max: 0.4,
        step: 0.005,
        key: { inc: "7", dec: "8", step: 0.01, shiftStep: 0.04 },
      },
      {
        id: "seaSpeed",
        label: "Sea Speed",
        uniform: "uSeaSpeed",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 2.0,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "camHeight",
        label: "Cam Height",
        uniform: "uCamHeight",
        type: "float",
        value: 3.5,
        min: 1.0,
        max: 8.0,
        step: 0.1,
        key: { inc: "w", dec: "s", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "camDistance",
        label: "Cam Distance",
        uniform: "uCamDistance",
        type: "float",
        value: 5.0,
        min: 1.0,
        max: 10.0,
        step: 0.1,
        key: { inc: "e", dec: "d", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "camYaw",
        label: "Cam Yaw",
        uniform: "uCamYaw",
        type: "float",
        value: 0.0,
        min: -1.0,
        max: 1.0,
        step: 0.02,
        key: { inc: "r", dec: "f", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "camPitch",
        label: "Cam Pitch",
        uniform: "uCamPitch",
        type: "float",
        value: 0.0,
        min: -0.5,
        max: 0.5,
        step: 0.02,
        key: { inc: "t", dec: "g", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "skyBoost",
        label: "Sky Boost",
        uniform: "uSkyBoost",
        type: "float",
        value: 1.1,
        min: 0.6,
        max: 1.6,
        step: 0.02,
        key: { inc: "y", dec: "h", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "waterBrightness",
        label: "Water Bright",
        uniform: "uWaterBrightness",
        type: "float",
        value: 0.6,
        min: 0.2,
        max: 1.2,
        step: 0.02,
        key: { inc: "u", dec: "j", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "waterRed",
        label: "Water Red",
        uniform: "uWaterTint",
        type: "float",
        value: 0.0,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "i", dec: "k", step: 0.02 },
        component: 0,
      },
      {
        id: "waterGreen",
        label: "Water Green",
        uniform: "uWaterTint",
        type: "float",
        value: 0.09,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "o", dec: "l", step: 0.02 },
        component: 1,
      },
      {
        id: "waterBlue",
        label: "Water Blue",
        uniform: "uWaterTint",
        type: "float",
        value: 0.18,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "p", dec: ";", step: 0.02 },
        component: 2,
      },
    ],
  },
  {
    id: "sunset-plus",
    name: "Sunset Plus",
    description: "Volumetric sunset clouds with tunable turbulence and hue drift.",
    fragment: sunsetPlusFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 2.0,
        step: 0.02,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "turbulence",
        label: "Turbulence",
        uniform: "uTurbulence",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 2.5,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "cloudHeight",
        label: "Cloud Height",
        uniform: "uCloudHeight",
        type: "float",
        value: 0.3,
        min: 0.05,
        max: 1.0,
        step: 0.01,
        key: { inc: "5", dec: "6", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "stepBase",
        label: "Step Base",
        uniform: "uStepBase",
        type: "float",
        value: 0.005,
        min: 0.001,
        max: 0.02,
        step: 0.001,
        key: { inc: "7", dec: "8", step: 0.001, shiftStep: 0.004 },
      },
      {
        id: "stepScale",
        label: "Step Scale",
        uniform: "uStepScale",
        type: "float",
        value: 4.0,
        min: 2.0,
        max: 10.0,
        step: 0.2,
        key: { inc: "q", dec: "a", step: 0.2, shiftStep: 0.8 },
      },
      {
        id: "hueShift",
        label: "Hue Shift",
        uniform: "uHueShift",
        type: "float",
        value: 0.0,
        min: -3.0,
        max: 3.0,
        step: 0.05,
        key: { inc: "w", dec: "s", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "hueSpeed",
        label: "Hue Speed",
        uniform: "uHueSpeed",
        type: "float",
        value: 0.4,
        min: -2.0,
        max: 2.0,
        step: 0.05,
        key: { inc: "e", dec: "d", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "intensity",
        label: "Intensity",
        uniform: "uIntensity",
        type: "float",
        value: 1.0,
        min: 0.4,
        max: 2.5,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.05, shiftStep: 0.2 },
      },
    ],
  },
  {
    id: "diff-chromatic",
    name: "Chromatic Flow",
    description: "Two-channel diffusion with hue-as-angle and drifting color pulses.",
    fragment: diffChromaticFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    stateful: true,
    bufferSize: 384,
    params: [
      {
        id: "selfWeight",
        label: "Self Weight",
        uniform: "uSelfWeight",
        type: "float",
        value: 0.6,
        min: 0.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "neighborWeight",
        label: "Neighbor Weight",
        uniform: "uNeighborWeight",
        type: "float",
        value: 1.0,
        min: 0.05,
        max: 2.0,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "decay",
        label: "Decay",
        uniform: "uDecay",
        type: "float",
        value: 0.998,
        min: 0.9,
        max: 0.9999,
        step: 0.0005,
        key: { inc: "5", dec: "6", step: 0.001, shiftStep: 0.005 },
      },
      {
        id: "rotate",
        label: "Rotate",
        uniform: "uRotate",
        type: "float",
        value: 0.02,
        min: -0.2,
        max: 0.2,
        step: 0.005,
        key: { inc: "7", dec: "8", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "injectAmp",
        label: "Inject Amp",
        uniform: "uInjectAmp",
        type: "float",
        value: 0.35,
        min: 0.0,
        max: 2.0,
        step: 0.02,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "injectRadius",
        label: "Inject Radius",
        uniform: "uInjectRadius",
        type: "float",
        value: 0.06,
        min: 0.01,
        max: 0.25,
        step: 0.005,
        key: { inc: "w", dec: "s", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "valueGain",
        label: "Value Gain",
        uniform: "uValueGain",
        type: "float",
        value: 2.2,
        min: 0.2,
        max: 6.0,
        step: 0.05,
        key: { inc: "e", dec: "d", step: 0.1, shiftStep: 0.3 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "zippy-zaps",
    name: "Zippy Zaps Plus",
    description: "Tanh-warped chromatic flow with twistable energy and glow.",
    fragment: zippyZapsFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "zoom",
        label: "Zoom",
        uniform: "uZoom",
        type: "float",
        value: 0.2,
        min: 0.05,
        max: 0.5,
        step: 0.005,
        key: { inc: "1", dec: "2", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 1.0,
        min: 0.1,
        max: 3.0,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "twist",
        label: "Twist",
        uniform: "uTwist",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 2.0,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "warp",
        label: "Warp",
        uniform: "uWarp",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 2.0,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "pulse",
        label: "Pulse",
        uniform: "uPulse",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 2.5,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "iterLimit",
        label: "Iter Limit",
        uniform: "uIterLimit",
        type: "float",
        value: 19.0,
        min: 4.0,
        max: 19.0,
        step: 1.0,
        key: { inc: "w", dec: "s", step: 1.0, shiftStep: 3.0 },
      },
      {
        id: "glow",
        label: "Glow",
        uniform: "uGlow",
        type: "float",
        value: 1.0,
        min: 0.4,
        max: 2.0,
        step: 0.05,
        key: { inc: "e", dec: "d", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "colorShift",
        label: "Color Shift",
        uniform: "uColorShift",
        type: "float",
        value: 0.0,
        min: 0.0,
        max: 6.283,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "offsetX",
        label: "Offset X",
        uniform: "uOffsetX",
        type: "float",
        value: 0.0,
        min: -0.5,
        max: 0.5,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "offsetY",
        label: "Offset Y",
        uniform: "uOffsetY",
        type: "float",
        value: 0.0,
        min: -0.5,
        max: 0.5,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.02, shiftStep: 0.08 },
      },
    ],
  },
  {
    id: "space-lightning-plus",
    name: "Space Lightning Plus",
    description: "Funky ion bolts with twistable arcs, palette waves, and core glow.",
    fragment: spaceLightningPlusFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 0.35,
        min: 0.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "zoom",
        label: "Zoom",
        uniform: "uZoom",
        type: "float",
        value: 0.9,
        min: 0.3,
        max: 1.8,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "spin",
        label: "Spin",
        uniform: "uSpin",
        type: "float",
        value: 0.4,
        min: -2.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "5", dec: "6", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "twist",
        label: "Twist",
        uniform: "uTwist",
        type: "float",
        value: 1.2,
        min: 0.0,
        max: 3.0,
        step: 0.02,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "warp",
        label: "Warp",
        uniform: "uWarp",
        type: "float",
        value: 0.9,
        min: 0.0,
        max: 2.0,
        step: 0.02,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "pulse",
        label: "Pulse",
        uniform: "uPulse",
        type: "float",
        value: 1.1,
        min: 0.0,
        max: 3.0,
        step: 0.02,
        key: { inc: "w", dec: "s", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "boltDensity",
        label: "Bolt Density",
        uniform: "uBoltDensity",
        type: "float",
        value: 6.5,
        min: 1.0,
        max: 20.0,
        step: 0.1,
        key: { inc: "e", dec: "d", step: 0.1, shiftStep: 0.3 },
      },
      {
        id: "boltSharpness",
        label: "Bolt Sharpness",
        uniform: "uBoltSharpness",
        type: "float",
        value: 0.9,
        min: 0.1,
        max: 2.5,
        step: 0.02,
        key: { inc: "r", dec: "f", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "boltIntensity",
        label: "Bolt Intensity",
        uniform: "uBoltIntensity",
        type: "float",
        value: 1.2,
        min: 0.2,
        max: 3.0,
        step: 0.05,
        key: { inc: "t", dec: "g", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "arcSteps",
        label: "Arc Steps",
        uniform: "uArcSteps",
        type: "float",
        value: 40.0,
        min: 6.0,
        max: 80.0,
        step: 1.0,
        key: { inc: "y", dec: "h", step: 1.0, shiftStep: 5.0 },
      },
      {
        id: "coreSize",
        label: "Core Size",
        uniform: "uCoreSize",
        type: "float",
        value: 0.25,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "u", dec: "j", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "coreGlow",
        label: "Core Glow",
        uniform: "uCoreGlow",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 2.0,
        step: 0.02,
        key: { inc: "i", dec: "k", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "noiseAmp",
        label: "Noise Amp",
        uniform: "uNoiseAmp",
        type: "float",
        value: 0.25,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "o", dec: "l", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "paletteShift",
        label: "Palette Shift",
        uniform: "uPaletteShift",
        type: "float",
        value: 0.0,
        min: 0.0,
        max: 6.283,
        step: 0.05,
        key: { inc: "p", dec: ";", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "primaryRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.08,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "primaryGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.7,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "primaryBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "secondaryRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.9,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "secondaryGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "secondaryBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "accentRed",
        label: "Accent Red",
        uniform: "uColorAccent",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "accentGreen",
        label: "Accent Green",
        uniform: "uColorAccent",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "accentBlue",
        label: "Accent Blue",
        uniform: "uColorAccent",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "lightning-blade-plus",
    name: "Lightning Blade Plus",
    description: "Flaring core with jittered blades and controllable noise flicker.",
    fragment: lightningBladePlusFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 3.0,
        step: 0.02,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "zoom",
        label: "Zoom",
        uniform: "uZoom",
        type: "float",
        value: 0.4,
        min: 0.1,
        max: 1.2,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "coreRadius",
        label: "Core Radius",
        uniform: "uCoreRadius",
        type: "float",
        value: 0.02,
        min: 0.005,
        max: 0.1,
        step: 0.001,
        key: { inc: "5", dec: "6", step: 0.002, shiftStep: 0.01 },
      },
      {
        id: "coreNoiseScale",
        label: "Core Noise Scale",
        uniform: "uCoreNoiseScale",
        type: "float",
        value: 50.0,
        min: 5.0,
        max: 120.0,
        step: 0.5,
        key: { inc: "7", dec: "8", step: 1.0, shiftStep: 5.0 },
      },
      {
        id: "coreNoiseAmp",
        label: "Core Noise Amp",
        uniform: "uCoreNoiseAmp",
        type: "float",
        value: 0.02,
        min: 0.0,
        max: 0.08,
        step: 0.001,
        key: { inc: "q", dec: "a", step: 0.002, shiftStep: 0.01 },
      },
      {
        id: "coreIntensity",
        label: "Core Intensity",
        uniform: "uCoreIntensity",
        type: "float",
        value: 0.6,
        min: 0.1,
        max: 2.0,
        step: 0.02,
        key: { inc: "w", dec: "s", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "boltCount",
        label: "Bolt Count",
        uniform: "uBoltCount",
        type: "int",
        value: 4,
        min: 1,
        max: 10,
        step: 1,
        key: { inc: "e", dec: "d", step: 1, shiftStep: 2 },
      },
      {
        id: "boltLengthMin",
        label: "Bolt Length Min",
        uniform: "uBoltLengthMin",
        type: "float",
        value: 0.12,
        min: 0.05,
        max: 0.4,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.01, shiftStep: 0.05 },
      },
      {
        id: "boltLengthMax",
        label: "Bolt Length Max",
        uniform: "uBoltLengthMax",
        type: "float",
        value: 0.35,
        min: 0.1,
        max: 0.7,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.01, shiftStep: 0.05 },
      },
      {
        id: "boltWidth",
        label: "Bolt Width",
        uniform: "uBoltWidth",
        type: "float",
        value: 0.0006,
        min: 0.0001,
        max: 0.004,
        step: 0.0001,
        key: { inc: "y", dec: "h", step: 0.0002, shiftStep: 0.001 },
      },
      {
        id: "boltWiggle",
        label: "Bolt Wiggle",
        uniform: "uBoltWiggle",
        type: "float",
        value: 0.03,
        min: 0.0,
        max: 0.15,
        step: 0.005,
        key: { inc: "u", dec: "j", step: 0.005, shiftStep: 0.02 },
      },
      {
        id: "boltNoiseScale",
        label: "Bolt Noise Scale",
        uniform: "uBoltNoiseScale",
        type: "float",
        value: 20.0,
        min: 5.0,
        max: 60.0,
        step: 0.5,
        key: { inc: "i", dec: "k", step: 1.0, shiftStep: 3.0 },
      },
      {
        id: "boltNoiseSpeed",
        label: "Bolt Noise Speed",
        uniform: "uBoltNoiseSpeed",
        type: "float",
        value: 2.0,
        min: 0.0,
        max: 8.0,
        step: 0.05,
        key: { inc: "o", dec: "l", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "boltSecondaryScale",
        label: "Bolt Secondary",
        uniform: "uBoltSecondaryScale",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 1.5,
        step: 0.02,
        key: { inc: "p", dec: ";", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "boltIntensity",
        label: "Bolt Intensity",
        uniform: "uBoltIntensity",
        type: "float",
        value: 0.25,
        min: 0.05,
        max: 1.2,
        step: 0.02,
      },
      {
        id: "flickerSpeed",
        label: "Flicker Speed",
        uniform: "uFlickerSpeed",
        type: "float",
        value: 4.0,
        min: 0.0,
        max: 12.0,
        step: 0.1,
      },
      {
        id: "angleJitter",
        label: "Angle Jitter",
        uniform: "uAngleJitter",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 2.0,
        step: 0.02,
      },
      {
        id: "twist",
        label: "Twist",
        uniform: "uTwist",
        type: "float",
        value: 0.125,
        min: 0.0,
        max: 0.5,
        step: 0.005,
      },
      {
        id: "noiseOctaves",
        label: "Noise Octaves",
        uniform: "uNoiseOctaves",
        type: "int",
        value: 3,
        min: 1,
        max: 6,
        step: 1,
      },
      {
        id: "primaryRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.1,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "primaryGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.1,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "primaryBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "secondaryRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.1,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "secondaryGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "secondaryBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "accentRed",
        label: "Accent Red",
        uniform: "uColorAccent",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "accentGreen",
        label: "Accent Green",
        uniform: "uColorAccent",
        type: "float",
        value: 0.3,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "accentBlue",
        label: "Accent Blue",
        uniform: "uColorAccent",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "mandelbulb-inside-plus",
    name: "Inside the Mandelbulb Plus",
    description: "Raymarched mandelbulb interior with tunable optics and palette glow.",
    fragment: mandelbulbInsidePlusFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 3.0,
        step: 0.02,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "power",
        label: "Power",
        uniform: "uPower",
        type: "float",
        value: 8.0,
        min: 2.0,
        max: 12.0,
        step: 0.1,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "bulbSpin",
        label: "Bulb Spin",
        uniform: "uBulbSpin",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.5,
        step: 0.01,
        key: { inc: "5", dec: "6", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "loops",
        label: "Loops",
        uniform: "uLoops",
        type: "int",
        value: 2,
        min: 1,
        max: 6,
        step: 1,
        key: { inc: "7", dec: "8", step: 1, shiftStep: 1 },
      },
      {
        id: "rayMarches",
        label: "Ray Marches",
        uniform: "uRayMarches",
        type: "int",
        value: 60,
        min: 20,
        max: 96,
        step: 1,
        key: { inc: "q", dec: "a", step: 1, shiftStep: 5 },
      },
      {
        id: "maxRayLength",
        label: "Max Ray Length",
        uniform: "uMaxRayLength",
        type: "float",
        value: 20.0,
        min: 5.0,
        max: 40.0,
        step: 0.5,
        key: { inc: "w", dec: "s", step: 0.5, shiftStep: 2.0 },
      },
      {
        id: "tolerance",
        label: "Tolerance",
        uniform: "uTolerance",
        type: "float",
        value: 0.0001,
        min: 0.00001,
        max: 0.001,
        step: 0.00001,
        key: { inc: "e", dec: "d", step: 0.00002, shiftStep: 0.0001 },
      },
      {
        id: "normOffset",
        label: "Normal Offset",
        uniform: "uNormOffset",
        type: "float",
        value: 0.005,
        min: 0.001,
        max: 0.02,
        step: 0.0005,
        key: { inc: "r", dec: "f", step: 0.0005, shiftStep: 0.002 },
      },
      {
        id: "bounces",
        label: "Bounces",
        uniform: "uBounces",
        type: "int",
        value: 5,
        min: 1,
        max: 5,
        step: 1,
        key: { inc: "t", dec: "g", step: 1, shiftStep: 1 },
      },
      {
        id: "initStep",
        label: "Init Step",
        uniform: "uInitStep",
        type: "float",
        value: 0.1,
        min: 0.01,
        max: 0.3,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.01, shiftStep: 0.05 },
      },
      {
        id: "rotSpeedX",
        label: "Rot Speed X",
        uniform: "uRotSpeedX",
        type: "float",
        value: 0.2,
        min: -1.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "u", dec: "j", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "rotSpeedY",
        label: "Rot Speed Y",
        uniform: "uRotSpeedY",
        type: "float",
        value: 0.3,
        min: -1.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "i", dec: "k", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "camDistance",
        label: "Cam Distance",
        uniform: "uCamDistance",
        type: "float",
        value: 5.0,
        min: 2.0,
        max: 10.0,
        step: 0.1,
        key: { inc: "o", dec: "l", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "camHeight",
        label: "Cam Height",
        uniform: "uCamHeight",
        type: "float",
        value: 2.0,
        min: 0.5,
        max: 5.0,
        step: 0.1,
        key: { inc: "p", dec: ";", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "fov",
        label: "FOV",
        uniform: "uFov",
        type: "float",
        value: 0.523,
        min: 0.3,
        max: 1.2,
        step: 0.01,
      },
      {
        id: "skyBoost",
        label: "Sky Boost",
        uniform: "uSkyBoost",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 3.0,
        step: 0.05,
      },
      {
        id: "glowBoost",
        label: "Glow Boost",
        uniform: "uGlowBoost",
        type: "float",
        value: 1.2,
        min: 0.0,
        max: 4.0,
        step: 0.05,
      },
      {
        id: "glowFalloff",
        label: "Glow Falloff",
        uniform: "uGlowFalloff",
        type: "float",
        value: 0.06,
        min: 0.01,
        max: 0.2,
        step: 0.005,
      },
      {
        id: "diffuseBoost",
        label: "Diffuse Boost",
        uniform: "uDiffuseBoost",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 3.0,
        step: 0.05,
      },
      {
        id: "matTransmit",
        label: "Mat Transmit",
        uniform: "uMatTransmit",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "matReflect",
        label: "Mat Reflect",
        uniform: "uMatReflect",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "refractIndex",
        label: "Refract Index",
        uniform: "uRefractIndex",
        type: "float",
        value: 1.05,
        min: 1.0,
        max: 2.0,
        step: 0.01,
      },
      {
        id: "hueShift",
        label: "Hue Shift",
        uniform: "uHueShift",
        type: "float",
        value: 0.0,
        min: -1.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "glowHueOffset",
        label: "Glow Hue Offset",
        uniform: "uGlowHueOffset",
        type: "float",
        value: 0.065,
        min: -0.5,
        max: 0.5,
        step: 0.005,
      },
      {
        id: "nebulaMix",
        label: "Nebula Mix",
        uniform: "uNebulaMix",
        type: "float",
        value: 0.0,
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "nebulaHueShift",
        label: "Nebula Hue",
        uniform: "uNebulaHueShift",
        type: "float",
        value: 0.12,
        min: -1.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "nebulaSat",
        label: "Nebula Sat",
        uniform: "uNebulaSat",
        type: "float",
        value: 0.9,
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "nebulaVal",
        label: "Nebula Val",
        uniform: "uNebulaVal",
        type: "float",
        value: 1.6,
        min: 0.2,
        max: 3.0,
        step: 0.02,
      },
      {
        id: "nebulaGlowHue",
        label: "Nebula Glow Hue",
        uniform: "uNebulaGlowHue",
        type: "float",
        value: 0.35,
        min: -1.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "nebulaGlowBoost",
        label: "Nebula Glow",
        uniform: "uNebulaGlowBoost",
        type: "float",
        value: 1.6,
        min: 0.0,
        max: 4.0,
        step: 0.05,
      },
      {
        id: "skySat",
        label: "Sky Saturation",
        uniform: "uSkySat",
        type: "float",
        value: 0.86,
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "skyVal",
        label: "Sky Value",
        uniform: "uSkyVal",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 2.0,
        step: 0.02,
      },
      {
        id: "glowSat",
        label: "Glow Saturation",
        uniform: "uGlowSat",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "glowVal",
        label: "Glow Value",
        uniform: "uGlowVal",
        type: "float",
        value: 6.0,
        min: 0.5,
        max: 8.0,
        step: 0.1,
      },
      {
        id: "diffuseSat",
        label: "Diffuse Saturation",
        uniform: "uDiffuseSat",
        type: "float",
        value: 0.85,
        min: 0.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "diffuseVal",
        label: "Diffuse Value",
        uniform: "uDiffuseVal",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 2.0,
        step: 0.02,
      },
      {
        id: "beerRed",
        label: "Beer Red",
        uniform: "uBeerColor",
        type: "float",
        value: 0.02,
        min: 0.0,
        max: 0.2,
        step: 0.005,
        component: 0,
      },
      {
        id: "beerGreen",
        label: "Beer Green",
        uniform: "uBeerColor",
        type: "float",
        value: 0.08,
        min: 0.0,
        max: 0.2,
        step: 0.005,
        component: 1,
      },
      {
        id: "beerBlue",
        label: "Beer Blue",
        uniform: "uBeerColor",
        type: "float",
        value: 0.12,
        min: 0.0,
        max: 0.2,
        step: 0.005,
        component: 2,
      },
      {
        id: "lightX",
        label: "Light X",
        uniform: "uLightPos",
        type: "float",
        value: 0.0,
        min: -20.0,
        max: 20.0,
        step: 0.5,
        component: 0,
      },
      {
        id: "lightY",
        label: "Light Y",
        uniform: "uLightPos",
        type: "float",
        value: 10.0,
        min: -5.0,
        max: 25.0,
        step: 0.5,
        component: 1,
      },
      {
        id: "lightZ",
        label: "Light Z",
        uniform: "uLightPos",
        type: "float",
        value: 0.0,
        min: -20.0,
        max: 20.0,
        step: 0.5,
        component: 2,
      },
    ],
  },
  {
    id: "auroras-plus",
    name: "Auroras Plus",
    description: "Volumetric auroras with tunable trails, palette waves, and sky glare.",
    fragment: aurorasPlusFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 3.0,
        step: 0.02,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "auroraSpeed",
        label: "Aurora Speed",
        uniform: "uAuroraSpeed",
        type: "float",
        value: 0.06,
        min: 0.0,
        max: 0.2,
        step: 0.005,
        key: { inc: "3", dec: "4", step: 0.005, shiftStep: 0.02 },
      },
      {
        id: "auroraScale",
        label: "Aurora Scale",
        uniform: "uAuroraScale",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 3.0,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "auroraWarp",
        label: "Aurora Warp",
        uniform: "uAuroraWarp",
        type: "float",
        value: 0.35,
        min: 0.0,
        max: 1.0,
        step: 0.02,
        key: { inc: "7", dec: "8", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "auroraSteps",
        label: "Aurora Steps",
        uniform: "uAuroraSteps",
        type: "int",
        value: 50,
        min: 8,
        max: 64,
        step: 1,
        key: { inc: "q", dec: "a", step: 1, shiftStep: 4 },
      },
      {
        id: "auroraBase",
        label: "Aurora Base",
        uniform: "uAuroraBase",
        type: "float",
        value: 0.8,
        min: 0.2,
        max: 1.6,
        step: 0.02,
        key: { inc: "w", dec: "s", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "auroraStride",
        label: "Aurora Stride",
        uniform: "uAuroraStride",
        type: "float",
        value: 0.002,
        min: 0.0002,
        max: 0.01,
        step: 0.0002,
        key: { inc: "e", dec: "d", step: 0.0002, shiftStep: 0.001 },
      },
      {
        id: "auroraCurve",
        label: "Aurora Curve",
        uniform: "uAuroraCurve",
        type: "float",
        value: 1.4,
        min: 0.8,
        max: 2.2,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "auroraIntensity",
        label: "Aurora Intensity",
        uniform: "uAuroraIntensity",
        type: "float",
        value: 1.8,
        min: 0.2,
        max: 4.0,
        step: 0.05,
        key: { inc: "t", dec: "g", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "trailBlend",
        label: "Trail Blend",
        uniform: "uTrailBlend",
        type: "float",
        value: 0.5,
        min: 0.1,
        max: 0.9,
        step: 0.02,
        key: { inc: "y", dec: "h", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "trailFalloff",
        label: "Trail Falloff",
        uniform: "uTrailFalloff",
        type: "float",
        value: 0.065,
        min: 0.01,
        max: 0.15,
        step: 0.005,
        key: { inc: "u", dec: "j", step: 0.005, shiftStep: 0.02 },
      },
      {
        id: "trailFade",
        label: "Trail Fade",
        uniform: "uTrailFade",
        type: "float",
        value: 2.5,
        min: 0.5,
        max: 5.0,
        step: 0.1,
        key: { inc: "i", dec: "k", step: 0.1, shiftStep: 0.4 },
      },
      {
        id: "ditherStrength",
        label: "Dither Strength",
        uniform: "uDitherStrength",
        type: "float",
        value: 0.006,
        min: 0.0,
        max: 0.02,
        step: 0.0005,
        key: { inc: "o", dec: "l", step: 0.0005, shiftStep: 0.002 },
      },
      {
        id: "horizonFade",
        label: "Horizon Fade",
        uniform: "uHorizonFade",
        type: "float",
        value: 0.01,
        min: 0.001,
        max: 0.05,
        step: 0.001,
        key: { inc: "p", dec: ";", step: 0.001, shiftStep: 0.005 },
      },
      {
        id: "camYaw",
        label: "Cam Yaw",
        uniform: "uCamYaw",
        type: "float",
        value: -0.1,
        min: -1.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "camPitch",
        label: "Cam Pitch",
        uniform: "uCamPitch",
        type: "float",
        value: 0.1,
        min: -1.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "camWobble",
        label: "Cam Wobble",
        uniform: "uCamWobble",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 0.6,
        step: 0.01,
      },
      {
        id: "camDistance",
        label: "Cam Distance",
        uniform: "uCamDistance",
        type: "float",
        value: 6.7,
        min: 4.0,
        max: 12.0,
        step: 0.1,
      },
      {
        id: "camHeight",
        label: "Cam Height",
        uniform: "uCamHeight",
        type: "float",
        value: 0.0,
        min: -1.0,
        max: 2.0,
        step: 0.05,
      },
      {
        id: "skyStrength",
        label: "Sky Strength",
        uniform: "uSkyStrength",
        type: "float",
        value: 0.63,
        min: 0.1,
        max: 2.0,
        step: 0.02,
      },
      {
        id: "starDensity",
        label: "Star Density",
        uniform: "uStarDensity",
        type: "float",
        value: 0.0005,
        min: 0.0,
        max: 0.005,
        step: 0.0001,
      },
      {
        id: "starIntensity",
        label: "Star Intensity",
        uniform: "uStarIntensity",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 2.0,
        step: 0.05,
      },
      {
        id: "reflectionStrength",
        label: "Reflection Strength",
        uniform: "uReflectionStrength",
        type: "float",
        value: 0.6,
        min: 0.0,
        max: 1.5,
        step: 0.05,
      },
      {
        id: "reflectionTint",
        label: "Reflection Tint",
        uniform: "uReflectionTint",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 2.0,
        step: 0.05,
      },
      {
        id: "reflectionFog",
        label: "Reflection Fog",
        uniform: "uReflectionFog",
        type: "float",
        value: 2.0,
        min: 0.0,
        max: 6.0,
        step: 0.1,
      },
      {
        id: "colorBand",
        label: "Color Band",
        uniform: "uColorBand",
        type: "float",
        value: 0.043,
        min: 0.0,
        max: 0.2,
        step: 0.002,
      },
      {
        id: "colorSpeed",
        label: "Color Speed",
        uniform: "uColorSpeed",
        type: "float",
        value: 0.0,
        min: -1.0,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "auroraRedA",
        label: "Aurora Red A",
        uniform: "uAuroraColorA",
        type: "float",
        value: 0.1,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "auroraGreenA",
        label: "Aurora Green A",
        uniform: "uAuroraColorA",
        type: "float",
        value: 0.9,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "auroraBlueA",
        label: "Aurora Blue A",
        uniform: "uAuroraColorA",
        type: "float",
        value: 0.6,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "auroraRedB",
        label: "Aurora Red B",
        uniform: "uAuroraColorB",
        type: "float",
        value: 0.6,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "auroraGreenB",
        label: "Aurora Green B",
        uniform: "uAuroraColorB",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "auroraBlueB",
        label: "Aurora Blue B",
        uniform: "uAuroraColorB",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "auroraRedC",
        label: "Aurora Red C",
        uniform: "uAuroraColorC",
        type: "float",
        value: 0.1,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "auroraGreenC",
        label: "Aurora Green C",
        uniform: "uAuroraColorC",
        type: "float",
        value: 0.6,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "auroraBlueC",
        label: "Aurora Blue C",
        uniform: "uAuroraColorC",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "bgRedA",
        label: "BG Red A",
        uniform: "uBgColorA",
        type: "float",
        value: 0.05,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "bgGreenA",
        label: "BG Green A",
        uniform: "uBgColorA",
        type: "float",
        value: 0.1,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "bgBlueA",
        label: "BG Blue A",
        uniform: "uBgColorA",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
      {
        id: "bgRedB",
        label: "BG Red B",
        uniform: "uBgColorB",
        type: "float",
        value: 0.1,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 0,
      },
      {
        id: "bgGreenB",
        label: "BG Green B",
        uniform: "uBgColorB",
        type: "float",
        value: 0.05,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 1,
      },
      {
        id: "bgBlueB",
        label: "BG Blue B",
        uniform: "uBgColorB",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        component: 2,
      },
    ],
  },
  {
    id: "diff-edge-flow",
    name: "Edge Flow Vectors",
    description: "Diffusive scalar field rendered as glowing edge-flow vectors.",
    fragment: diffEdgeFlowFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    stateful: true,
    bufferSize: 384,
    params: [
      {
        id: "selfWeight",
        label: "Self Weight",
        uniform: "uSelfWeight",
        type: "float",
        value: 0.6,
        min: 0.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "neighborWeight",
        label: "Neighbor Weight",
        uniform: "uNeighborWeight",
        type: "float",
        value: 1.0,
        min: 0.05,
        max: 2.0,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "decay",
        label: "Decay",
        uniform: "uDecay",
        type: "float",
        value: 0.996,
        min: 0.9,
        max: 0.9999,
        step: 0.0005,
        key: { inc: "5", dec: "6", step: 0.001, shiftStep: 0.005 },
      },
      {
        id: "blobAmp",
        label: "Blob Amp",
        uniform: "uBlobAmp",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 2.0,
        step: 0.02,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "blobRadius",
        label: "Blob Radius",
        uniform: "uBlobRadius",
        type: "float",
        value: 0.07,
        min: 0.01,
        max: 0.25,
        step: 0.005,
        key: { inc: "q", dec: "a", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "speed",
        label: "Speed",
        uniform: "uSpeed",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 3.0,
        step: 0.05,
        key: { inc: "w", dec: "s", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "flowGain",
        label: "Flow Gain",
        uniform: "uFlowGain",
        type: "float",
        value: 3.0,
        min: 0.2,
        max: 8.0,
        step: 0.1,
        key: { inc: "e", dec: "d", step: 0.2, shiftStep: 0.6 },
      },
      {
        id: "flowThreshold",
        label: "Flow Threshold",
        uniform: "uFlowThreshold",
        type: "float",
        value: 0.02,
        min: 0.0,
        max: 0.2,
        step: 0.005,
        key: { inc: "r", dec: "f", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "diff-threshold",
    name: "Threshold Feedback",
    description: "Diffusion with nonlinear feedback for digital fungus crackle.",
    fragment: diffThresholdFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    stateful: true,
    bufferSize: 192,
    params: [
      {
        id: "selfWeight",
        label: "Self Weight",
        uniform: "uSelfWeight",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "neighborWeight",
        label: "Neighbor Weight",
        uniform: "uNeighborWeight",
        type: "float",
        value: 1.0,
        min: 0.05,
        max: 2.0,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "decay",
        label: "Decay",
        uniform: "uDecay",
        type: "float",
        value: 0.995,
        min: 0.9,
        max: 0.9999,
        step: 0.0005,
        key: { inc: "5", dec: "6", step: 0.001, shiftStep: 0.005 },
      },
      {
        id: "threshold",
        label: "Threshold",
        uniform: "uThreshold",
        type: "float",
        value: 0.5,
        min: 0.1,
        max: 0.9,
        step: 0.01,
        key: { inc: "7", dec: "8", step: 0.02, shiftStep: 0.06 },
      },
      {
        id: "sharpness",
        label: "Sharpness",
        uniform: "uSharpness",
        type: "float",
        value: 18.0,
        min: 1.0,
        max: 40.0,
        step: 0.5,
        key: { inc: "q", dec: "a", step: 1.0, shiftStep: 4.0 },
      },
      {
        id: "noiseAmp",
        label: "Noise Amp",
        uniform: "uNoiseAmp",
        type: "float",
        value: 0.08,
        min: 0.0,
        max: 0.5,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.02, shiftStep: 0.06 },
      },
      {
        id: "turbulence",
        label: "Turbulence",
        uniform: "uTurbulence",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 2.0,
        step: 0.05,
        key: { inc: "e", dec: "d", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "injectAmp",
        label: "Inject Amp",
        uniform: "uInjectAmp",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.5,
        step: 0.02,
        key: { inc: "e", dec: "d", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "injectRadius",
        label: "Inject Radius",
        uniform: "uInjectRadius",
        type: "float",
        value: 0.06,
        min: 0.01,
        max: 0.25,
        step: 0.005,
        key: { inc: "r", dec: "f", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "speed",
        label: "Speed",
        uniform: "uSpeed",
        type: "float",
        value: 0.9,
        min: 0.0,
        max: 3.0,
        step: 0.05,
        key: { inc: "t", dec: "g", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
];







