import neonFrag from "./shaders/neon_isoclines.frag?raw";
import tanhFrag from "./shaders/terrain_tanh_isoclines.frag?raw";
import tunnelFrag from "./shaders/brownian_loop_tunnel.frag?raw";
import kochFrag from "./shaders/koch_snowflake.frag?raw";
import quasiFrag from "./shaders/quasi_snowflake.frag?raw";

export type KeyBinding = {
  inc: string;
  dec: string;
  step: number;
  shiftStep?: number;
};

export type ParamType = "float" | "int" | "seed";

export type ParamSpec = {
  id: string;
  label: string;
  uniform: string;
  type: ParamType;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  key?: KeyBinding;
  component?: 0 | 1 | 2;
};

export type AnimationConfig = {
  id: string;
  name: string;
  description: string;
  fragment: string;
  resolutionUniform: string;
  timeUniform: string;
  timeMode: "phase" | "seconds" | "looped";
  loopDuration?: number;
  loopUniform?: string;
  params: ParamSpec[];
};

export const animations: AnimationConfig[] = [
  {
    id: "neon",
    name: "Neon Isoclines",
    description: "Electric contour bands driven by seeded radial harmonics.",
    fragment: neonFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uPhase",
    timeMode: "phase",
    loopDuration: 8,
    params: [
      {
        id: "components",
        label: "Components",
        uniform: "uComponents",
        type: "int",
        value: 64,
        min: 1,
        max: 64,
        step: 1,
        key: { inc: "q", dec: "a", step: 1, shiftStep: 10 },
      },
      {
        id: "isoBands",
        label: "Iso Bands",
        uniform: "uIsoBands",
        type: "int",
        value: 8,
        min: 1,
        max: 64,
        step: 1,
        key: { inc: "w", dec: "s", step: 1, shiftStep: 10 },
      },
      {
        id: "lineThickness",
        label: "Line Thickness",
        uniform: "uLineThickness",
        type: "float",
        value: 0.25,
        min: 0.01,
        max: 0.75,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.02, shiftStep: 0.05 },
      },
      {
        id: "noiseAmount",
        label: "Noise Amount",
        uniform: "uNoiseAmount",
        type: "float",
        value: 2.5,
        min: 0,
        max: 5,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.1, shiftStep: 0.25 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "tanh-terrain",
    name: "Tanh Terrain Isoclines",
    description: "Tanh warped contours with bubbling noise and topo glow.",
    fragment: tanhFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uPhase",
    timeMode: "phase",
    loopDuration: 8,
    params: [
      {
        id: "scale",
        label: "Scale",
        uniform: "uScale",
        type: "float",
        value: 2.1,
        min: 0.1,
        max: 6,
        step: 0.05,
        key: { inc: "1", dec: "2", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "octaves",
        label: "Octaves",
        uniform: "uOctaves",
        type: "int",
        value: 4,
        min: 1,
        max: 12,
        step: 1,
        key: { inc: "3", dec: "4", step: 1 },
      },
      {
        id: "lacunarity",
        label: "Lacunarity",
        uniform: "uLacunarity",
        type: "float",
        value: 1.4,
        min: 1.01,
        max: 3,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.05, shiftStep: 0.15 },
      },
      {
        id: "gain",
        label: "Gain",
        uniform: "uGain",
        type: "float",
        value: 0.5,
        min: 0.01,
        max: 0.99,
        step: 0.01,
        key: { inc: "7", dec: "8", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "isoBands",
        label: "Iso Bands",
        uniform: "uIsoBands",
        type: "int",
        value: 16,
        min: 1,
        max: 96,
        step: 1,
        key: { inc: "q", dec: "a", step: 4, shiftStep: 12 },
      },
      {
        id: "lineThickness",
        label: "Line Thickness",
        uniform: "uLineThickness",
        type: "float",
        value: 0.2,
        min: 0.02,
        max: 0.75,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.02, shiftStep: 0.06 },
      },
      {
        id: "bubbleAmp",
        label: "Bubble Amp",
        uniform: "uBubbleAmp",
        type: "float",
        value: 0.26,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "bubbleFreq",
        label: "Bubble Freq",
        uniform: "uBubbleFreq",
        type: "float",
        value: 2.0,
        min: 0,
        max: 6,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.25, shiftStep: 0.75 },
      },
      {
        id: "bubbleDetail",
        label: "Bubble Detail",
        uniform: "uBubbleDetail",
        type: "float",
        value: 1.2,
        min: 0.1,
        max: 3,
        step: 0.05,
        key: { inc: "t", dec: "g", step: 0.1, shiftStep: 0.3 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "tunnel",
    name: "Brownian Loop Tunnel",
    description: "Looped tunnel with Brownian noise, fog, and hue spin.",
    fragment: tunnelFrag,
    resolutionUniform: "iResolution",
    timeUniform: "iTime",
    timeMode: "looped",
    loopDuration: 8,
    loopUniform: "uLoopDuration",
    params: [
      {
        id: "speed",
        label: "Speed",
        uniform: "uSpeed",
        type: "float",
        value: 1.0,
        min: 0.1,
        max: 4,
        step: 0.05,
        key: { inc: "1", dec: "2", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "twist",
        label: "Twist",
        uniform: "uTwist",
        type: "float",
        value: 4.0,
        min: 0,
        max: 10,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "noiseScale",
        label: "Noise Scale",
        uniform: "uNoiseScale",
        type: "float",
        value: 1.9,
        min: 0.1,
        max: 4,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "noiseAmp",
        label: "Noise Amp",
        uniform: "uNoiseAmp",
        type: "float",
        value: 0.5,
        min: 0,
        max: 2,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "colorCycle",
        label: "Color Cycle",
        uniform: "uColorCycle",
        type: "float",
        value: 1.0,
        min: 0,
        max: 4,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "fogDensity",
        label: "Fog Density",
        uniform: "uFogDensity",
        type: "float",
        value: 2.0,
        min: 0.1,
        max: 6,
        step: 0.05,
        key: { inc: "w", dec: "s", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "baseRed",
        label: "Base Red",
        uniform: "uBaseColor",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.05 },
        component: 0,
      },
      {
        id: "baseGreen",
        label: "Base Green",
        uniform: "uBaseColor",
        type: "float",
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.05 },
        component: 1,
      },
      {
        id: "baseBlue",
        label: "Base Blue",
        uniform: "uBaseColor",
        type: "float",
        value: 0.9,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.05 },
        component: 2,
      },
    ],
  },
  {
    id: "koch",
    name: "Koch Snowflake",
    description: "Iterative snowflake edges with neon glow mixing.",
    fragment: kochFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "iterations",
        label: "Iterations",
        uniform: "uIterations",
        type: "int",
        value: 4,
        min: 1,
        max: 8,
        step: 1,
        key: { inc: "1", dec: "2", step: 1 },
      },
      {
        id: "scale",
        label: "Scale",
        uniform: "uScale",
        type: "float",
        value: 0.8,
        min: 0.1,
        max: 2,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "rotation",
        label: "Rotation",
        uniform: "uRotation",
        type: "float",
        value: 0.2,
        min: -3,
        max: 3,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "glowIntensity",
        label: "Glow",
        uniform: "uGlowIntensity",
        type: "float",
        value: 2.0,
        min: 0,
        max: 5,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "primRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "q", dec: "a", step: 0.05 },
        component: 0,
      },
      {
        id: "primGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.6,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.05 },
        component: 1,
      },
      {
        id: "primBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.05 },
        component: 2,
      },
      {
        id: "secRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.05 },
        component: 0,
      },
      {
        id: "secGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.3,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.05 },
        component: 1,
      },
      {
        id: "secBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.6,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.05 },
        component: 2,
      },
    ],
  },
  {
    id: "quasi",
    name: "Quasi Snowflake",
    description: "Quasicrystal warp with a drifting snowflake outline.",
    fragment: quasiFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "iterations",
        label: "Iterations",
        uniform: "uIterations",
        type: "int",
        value: 6,
        min: 1,
        max: 8,
        step: 1,
        key: { inc: "1", dec: "2", step: 1 },
      },
      {
        id: "scale",
        label: "Scale",
        uniform: "uScale",
        type: "float",
        value: 1.1,
        min: 0.1,
        max: 3,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "rotation",
        label: "Rotation",
        uniform: "uRotation",
        type: "float",
        value: 0.0,
        min: -3,
        max: 3,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "glowIntensity",
        label: "Glow",
        uniform: "uGlowIntensity",
        type: "float",
        value: 0.9,
        min: 0,
        max: 3,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "primRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "q", dec: "a", step: 0.05 },
        component: 0,
      },
      {
        id: "primGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.8,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.05 },
        component: 1,
      },
      {
        id: "primBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.05 },
        component: 2,
      },
      {
        id: "secRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.02,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.02 },
        component: 0,
      },
      {
        id: "secGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.03,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.02 },
        component: 1,
      },
      {
        id: "secBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.05,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.02 },
        component: 2,
      },
    ],
  },
];
