import neonFrag from "./shaders/neon_isoclines.frag?raw";
import tanhFrag from "./shaders/terrain_tanh_isoclines.frag?raw";
import tunnelFrag from "./shaders/brownian_loop_tunnel.frag?raw";
import kochFrag from "./shaders/koch_snowflake.frag?raw";
import quasiFrag from "./shaders/quasi_snowflake.frag?raw";
import diffHeatFrag from "./shaders/diffusion_heat_blobs.frag?raw";
import diffChromaticFrag from "./shaders/diffusion_chromatic_flow.frag?raw";
import diffGrayScottFrag from "./shaders/diffusion_gray_scott.frag?raw";
import diffEdgeFlowFrag from "./shaders/diffusion_edge_flow.frag?raw";
import diffThresholdFrag from "./shaders/diffusion_threshold_feedback.frag?raw";
import prismFrag from "./shaders/prismatic_fold_raymarch.frag?raw";
import seascapeFrag from "./shaders/seascape_tdm.frag?raw";
import zippyZapsFrag from "./shaders/zippy_zaps.frag?raw";

export type KeyBinding = {
  inc: string;
  dec: string;
  step: number;
  shiftStep?: number;
};

export type ParamType = "float" | "int" | "seed";

export type ParamSpec = {
  id: string;
  label: string;
  uniform: string;
  type: ParamType;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  key?: KeyBinding;
  component?: 0 | 1 | 2;
};

export type AnimationConfig = {
  id: string;
  name: string;
  description: string;
  fragment: string;
  resolutionUniform: string;
  timeUniform: string;
  timeMode: "phase" | "seconds" | "looped";
  loopDuration?: number;
  loopUniform?: string;
  params: ParamSpec[];
  stateful?: boolean;
  bufferSize?: number;
  passUniform?: string;
  stateUniform?: string;
  gridUniform?: string;
};

export const animations: AnimationConfig[] = [
  {
    id: "neon",
    name: "Neon Isoclines",
    description: "Electric contour bands driven by seeded radial harmonics.",
    fragment: neonFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uPhase",
    timeMode: "phase",
    loopDuration: 8,
    params: [
      {
        id: "components",
        label: "Components",
        uniform: "uComponents",
        type: "int",
        value: 64,
        min: 1,
        max: 64,
        step: 1,
        key: { inc: "q", dec: "a", step: 1, shiftStep: 10 },
      },
      {
        id: "isoBands",
        label: "Iso Bands",
        uniform: "uIsoBands",
        type: "int",
        value: 8,
        min: 1,
        max: 64,
        step: 1,
        key: { inc: "w", dec: "s", step: 1, shiftStep: 10 },
      },
      {
        id: "lineThickness",
        label: "Line Thickness",
        uniform: "uLineThickness",
        type: "float",
        value: 0.25,
        min: 0.01,
        max: 0.75,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.02, shiftStep: 0.05 },
      },
      {
        id: "noiseAmount",
        label: "Noise Amount",
        uniform: "uNoiseAmount",
        type: "float",
        value: 2.5,
        min: 0,
        max: 5,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.1, shiftStep: 0.25 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "tanh-terrain",
    name: "Tanh Terrain Isoclines",
    description: "Tanh warped contours with bubbling noise and topo glow.",
    fragment: tanhFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uPhase",
    timeMode: "phase",
    loopDuration: 8,
    params: [
      {
        id: "scale",
        label: "Scale",
        uniform: "uScale",
        type: "float",
        value: 2.1,
        min: 0.1,
        max: 6,
        step: 0.05,
        key: { inc: "1", dec: "2", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "octaves",
        label: "Octaves",
        uniform: "uOctaves",
        type: "int",
        value: 4,
        min: 1,
        max: 12,
        step: 1,
        key: { inc: "3", dec: "4", step: 1 },
      },
      {
        id: "lacunarity",
        label: "Lacunarity",
        uniform: "uLacunarity",
        type: "float",
        value: 1.4,
        min: 1.01,
        max: 3,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.05, shiftStep: 0.15 },
      },
      {
        id: "gain",
        label: "Gain",
        uniform: "uGain",
        type: "float",
        value: 0.5,
        min: 0.01,
        max: 0.99,
        step: 0.01,
        key: { inc: "7", dec: "8", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "isoBands",
        label: "Iso Bands",
        uniform: "uIsoBands",
        type: "int",
        value: 16,
        min: 1,
        max: 96,
        step: 1,
        key: { inc: "q", dec: "a", step: 4, shiftStep: 12 },
      },
      {
        id: "lineThickness",
        label: "Line Thickness",
        uniform: "uLineThickness",
        type: "float",
        value: 0.2,
        min: 0.02,
        max: 0.75,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.02, shiftStep: 0.06 },
      },
      {
        id: "bubbleAmp",
        label: "Bubble Amp",
        uniform: "uBubbleAmp",
        type: "float",
        value: 0.26,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "bubbleFreq",
        label: "Bubble Freq",
        uniform: "uBubbleFreq",
        type: "float",
        value: 2.0,
        min: 0,
        max: 6,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.25, shiftStep: 0.75 },
      },
      {
        id: "bubbleDetail",
        label: "Bubble Detail",
        uniform: "uBubbleDetail",
        type: "float",
        value: 1.2,
        min: 0.1,
        max: 3,
        step: 0.05,
        key: { inc: "t", dec: "g", step: 0.1, shiftStep: 0.3 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "tunnel",
    name: "Brownian Loop Tunnel",
    description: "Looped tunnel with Brownian noise, fog, and hue spin.",
    fragment: tunnelFrag,
    resolutionUniform: "iResolution",
    timeUniform: "iTime",
    timeMode: "looped",
    loopDuration: 8,
    loopUniform: "uLoopDuration",
    params: [
      {
        id: "speed",
        label: "Speed",
        uniform: "uSpeed",
        type: "float",
        value: 1.0,
        min: 0.1,
        max: 4,
        step: 0.05,
        key: { inc: "1", dec: "2", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "twist",
        label: "Twist",
        uniform: "uTwist",
        type: "float",
        value: 4.0,
        min: 0,
        max: 10,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "noiseScale",
        label: "Noise Scale",
        uniform: "uNoiseScale",
        type: "float",
        value: 1.9,
        min: 0.1,
        max: 4,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "noiseAmp",
        label: "Noise Amp",
        uniform: "uNoiseAmp",
        type: "float",
        value: 0.5,
        min: 0,
        max: 2,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "colorCycle",
        label: "Color Cycle",
        uniform: "uColorCycle",
        type: "float",
        value: 1.0,
        min: 0,
        max: 4,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "fogDensity",
        label: "Fog Density",
        uniform: "uFogDensity",
        type: "float",
        value: 2.0,
        min: 0.1,
        max: 6,
        step: 0.05,
        key: { inc: "w", dec: "s", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "baseRed",
        label: "Base Red",
        uniform: "uBaseColor",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.05 },
        component: 0,
      },
      {
        id: "baseGreen",
        label: "Base Green",
        uniform: "uBaseColor",
        type: "float",
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.05 },
        component: 1,
      },
      {
        id: "baseBlue",
        label: "Base Blue",
        uniform: "uBaseColor",
        type: "float",
        value: 0.9,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.05 },
        component: 2,
      },
    ],
  },
  {
    id: "prismatic-fold",
    name: "Prismatic Fold Raymarch",
    description: "Rotating folded planes with prismatic glow and controllable depth.",
    fragment: prismFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "iterations",
        label: "Iterations",
        uniform: "uIterations",
        type: "int",
        value: 8,
        min: 1,
        max: 24,
        step: 1,
        key: { inc: "1", dec: "2", step: 1, shiftStep: 4 },
      },
      {
        id: "rotateSpeed",
        label: "Rotate Speed",
        uniform: "uRotateSpeed",
        type: "float",
        value: 0.2,
        min: -1.5,
        max: 1.5,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "foldOffset",
        label: "Fold Offset",
        uniform: "uFoldOffset",
        type: "float",
        value: 0.5,
        min: 0.1,
        max: 1.0,
        step: 0.01,
        key: { inc: "5", dec: "6", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "stepScale",
        label: "Step Scale",
        uniform: "uStepScale",
        type: "float",
        value: 5.0,
        min: 1.5,
        max: 10.0,
        step: 0.1,
        key: { inc: "7", dec: "8", step: 0.2, shiftStep: 0.6 },
      },
      {
        id: "glow",
        label: "Glow",
        uniform: "uGlow",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 3.0,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "cameraDistance",
        label: "Camera Distance",
        uniform: "uCameraDistance",
        type: "float",
        value: 50.0,
        min: 10.0,
        max: 120.0,
        step: 1.0,
        key: { inc: "w", dec: "s", step: 1.0, shiftStep: 5.0 },
      },
      {
        id: "cameraSpin",
        label: "Camera Spin",
        uniform: "uCameraSpin",
        type: "float",
        value: 1.0,
        min: -3.0,
        max: 3.0,
        step: 0.05,
        key: { inc: "e", dec: "d", step: 0.1, shiftStep: 0.4 },
      },
      {
        id: "colorMix",
        label: "Color Mix",
        uniform: "uColorMix",
        type: "float",
        value: 0.35,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "alphaGain",
        label: "Alpha Gain",
        uniform: "uAlphaGain",
        type: "float",
        value: 1.0,
        min: 0.3,
        max: 2.0,
        step: 0.05,
        key: { inc: "t", dec: "g", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "primRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.05 },
        component: 0,
      },
      {
        id: "primGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.7,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "u", dec: "j", step: 0.05 },
        component: 1,
      },
      {
        id: "primBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.9,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "i", dec: "k", step: 0.05 },
        component: 2,
      },
      {
        id: "secRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "o", dec: "l", step: 0.05 },
        component: 0,
      },
      {
        id: "secGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "p", dec: ";", step: 0.05 },
        component: 1,
      },
      {
        id: "secBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "[", dec: "]", step: 0.05 },
        component: 2,
      },
    ],
  },
  {
    id: "koch",
    name: "Koch Snowflake",
    description: "Iterative snowflake edges with neon glow mixing.",
    fragment: kochFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "iterations",
        label: "Iterations",
        uniform: "uIterations",
        type: "int",
        value: 4,
        min: 1,
        max: 8,
        step: 1,
        key: { inc: "1", dec: "2", step: 1 },
      },
      {
        id: "scale",
        label: "Scale",
        uniform: "uScale",
        type: "float",
        value: 0.8,
        min: 0.1,
        max: 2,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "rotation",
        label: "Rotation",
        uniform: "uRotation",
        type: "float",
        value: 0.2,
        min: -3,
        max: 3,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "glowIntensity",
        label: "Glow",
        uniform: "uGlowIntensity",
        type: "float",
        value: 2.0,
        min: 0,
        max: 5,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "primRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "q", dec: "a", step: 0.05 },
        component: 0,
      },
      {
        id: "primGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.6,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.05 },
        component: 1,
      },
      {
        id: "primBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.05 },
        component: 2,
      },
      {
        id: "secRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.05 },
        component: 0,
      },
      {
        id: "secGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.3,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.05 },
        component: 1,
      },
      {
        id: "secBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.6,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.05 },
        component: 2,
      },
    ],
  },
  {
    id: "quasi",
    name: "Quasi Snowflake",
    description: "Quasicrystal warp with a drifting snowflake outline.",
    fragment: quasiFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "iterations",
        label: "Iterations",
        uniform: "uIterations",
        type: "int",
        value: 6,
        min: 1,
        max: 8,
        step: 1,
        key: { inc: "1", dec: "2", step: 1 },
      },
      {
        id: "scale",
        label: "Scale",
        uniform: "uScale",
        type: "float",
        value: 1.1,
        min: 0.1,
        max: 3,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "rotation",
        label: "Rotation",
        uniform: "uRotation",
        type: "float",
        value: 0.0,
        min: -3,
        max: 3,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "glowIntensity",
        label: "Glow",
        uniform: "uGlowIntensity",
        type: "float",
        value: 0.9,
        min: 0,
        max: 3,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "primRed",
        label: "Primary Red",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.2,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "q", dec: "a", step: 0.05 },
        component: 0,
      },
      {
        id: "primGreen",
        label: "Primary Green",
        uniform: "uColorPrimary",
        type: "float",
        value: 0.8,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.05 },
        component: 1,
      },
      {
        id: "primBlue",
        label: "Primary Blue",
        uniform: "uColorPrimary",
        type: "float",
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "e", dec: "d", step: 0.05 },
        component: 2,
      },
      {
        id: "secRed",
        label: "Secondary Red",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.02,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "r", dec: "f", step: 0.02 },
        component: 0,
      },
      {
        id: "secGreen",
        label: "Secondary Green",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.03,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.02 },
        component: 1,
      },
      {
        id: "secBlue",
        label: "Secondary Blue",
        uniform: "uColorSecondary",
        type: "float",
        value: 0.05,
        min: 0,
        max: 1,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.02 },
        component: 2,
      },
    ],
  },
  {
    id: "seascape",
    name: "Seascape",
    description: "Raymarched ocean with tunable swell and camera drift.",
    fragment: seascapeFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 0.3,
        min: 0.0,
        max: 1.5,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.02, shiftStep: 0.1 },
      },
      {
        id: "seaHeight",
        label: "Sea Height",
        uniform: "uSeaHeight",
        type: "float",
        value: 0.6,
        min: 0.1,
        max: 1.5,
        step: 0.02,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "seaChoppy",
        label: "Sea Choppy",
        uniform: "uSeaChoppy",
        type: "float",
        value: 4.0,
        min: 1.0,
        max: 7.0,
        step: 0.1,
        key: { inc: "5", dec: "6", step: 0.1, shiftStep: 0.4 },
      },
      {
        id: "seaFreq",
        label: "Sea Freq",
        uniform: "uSeaFreq",
        type: "float",
        value: 0.16,
        min: 0.05,
        max: 0.4,
        step: 0.005,
        key: { inc: "7", dec: "8", step: 0.01, shiftStep: 0.04 },
      },
      {
        id: "seaSpeed",
        label: "Sea Speed",
        uniform: "uSeaSpeed",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 2.0,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "camHeight",
        label: "Cam Height",
        uniform: "uCamHeight",
        type: "float",
        value: 3.5,
        min: 1.0,
        max: 8.0,
        step: 0.1,
        key: { inc: "w", dec: "s", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "camDistance",
        label: "Cam Distance",
        uniform: "uCamDistance",
        type: "float",
        value: 5.0,
        min: 1.0,
        max: 10.0,
        step: 0.1,
        key: { inc: "e", dec: "d", step: 0.1, shiftStep: 0.5 },
      },
      {
        id: "camYaw",
        label: "Cam Yaw",
        uniform: "uCamYaw",
        type: "float",
        value: 0.0,
        min: -1.0,
        max: 1.0,
        step: 0.02,
        key: { inc: "r", dec: "f", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "camPitch",
        label: "Cam Pitch",
        uniform: "uCamPitch",
        type: "float",
        value: 0.0,
        min: -0.5,
        max: 0.5,
        step: 0.02,
        key: { inc: "t", dec: "g", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "skyBoost",
        label: "Sky Boost",
        uniform: "uSkyBoost",
        type: "float",
        value: 1.1,
        min: 0.6,
        max: 1.6,
        step: 0.02,
        key: { inc: "y", dec: "h", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "waterBrightness",
        label: "Water Bright",
        uniform: "uWaterBrightness",
        type: "float",
        value: 0.6,
        min: 0.2,
        max: 1.2,
        step: 0.02,
        key: { inc: "u", dec: "j", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "waterRed",
        label: "Water Red",
        uniform: "uWaterTint",
        type: "float",
        value: 0.0,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "i", dec: "k", step: 0.02 },
        component: 0,
      },
      {
        id: "waterGreen",
        label: "Water Green",
        uniform: "uWaterTint",
        type: "float",
        value: 0.09,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "o", dec: "l", step: 0.02 },
        component: 1,
      },
      {
        id: "waterBlue",
        label: "Water Blue",
        uniform: "uWaterTint",
        type: "float",
        value: 0.18,
        min: 0.0,
        max: 1.0,
        step: 0.01,
        key: { inc: "p", dec: ";", step: 0.02 },
        component: 2,
      },
    ],
  },
  {
    id: "diff-heat",
    name: "Diffusion Heat Blobs",
    description: "Living stains from doubly-stochastic diffusion with drifting injectors.",
    fragment: diffHeatFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    stateful: true,
    bufferSize: 192,
    params: [
      {
        id: "selfWeight",
        label: "Self Weight",
        uniform: "uSelfWeight",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "neighborWeight",
        label: "Neighbor Weight",
        uniform: "uNeighborWeight",
        type: "float",
        value: 1.0,
        min: 0.05,
        max: 2.0,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "decay",
        label: "Decay",
        uniform: "uDecay",
        type: "float",
        value: 0.997,
        min: 0.9,
        max: 0.9999,
        step: 0.0005,
        key: { inc: "5", dec: "6", step: 0.001, shiftStep: 0.005 },
      },
      {
        id: "blobAmp",
        label: "Blob Amp",
        uniform: "uBlobAmp",
        type: "float",
        value: 0.6,
        min: 0.0,
        max: 2.0,
        step: 0.02,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "blobRadius",
        label: "Blob Radius",
        uniform: "uBlobRadius",
        type: "float",
        value: 0.08,
        min: 0.01,
        max: 0.25,
        step: 0.005,
        key: { inc: "q", dec: "a", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "speed",
        label: "Speed",
        uniform: "uSpeed",
        type: "float",
        value: 0.7,
        min: 0.0,
        max: 3.0,
        step: 0.05,
        key: { inc: "w", dec: "s", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "diff-chromatic",
    name: "Chromatic Flow",
    description: "Two-channel diffusion with hue-as-angle and drifting color pulses.",
    fragment: diffChromaticFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    stateful: true,
    bufferSize: 192,
    params: [
      {
        id: "selfWeight",
        label: "Self Weight",
        uniform: "uSelfWeight",
        type: "float",
        value: 0.6,
        min: 0.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "neighborWeight",
        label: "Neighbor Weight",
        uniform: "uNeighborWeight",
        type: "float",
        value: 1.0,
        min: 0.05,
        max: 2.0,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "decay",
        label: "Decay",
        uniform: "uDecay",
        type: "float",
        value: 0.998,
        min: 0.9,
        max: 0.9999,
        step: 0.0005,
        key: { inc: "5", dec: "6", step: 0.001, shiftStep: 0.005 },
      },
      {
        id: "rotate",
        label: "Rotate",
        uniform: "uRotate",
        type: "float",
        value: 0.02,
        min: -0.2,
        max: 0.2,
        step: 0.005,
        key: { inc: "7", dec: "8", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "injectAmp",
        label: "Inject Amp",
        uniform: "uInjectAmp",
        type: "float",
        value: 0.35,
        min: 0.0,
        max: 2.0,
        step: 0.02,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "injectRadius",
        label: "Inject Radius",
        uniform: "uInjectRadius",
        type: "float",
        value: 0.06,
        min: 0.01,
        max: 0.25,
        step: 0.005,
        key: { inc: "w", dec: "s", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "valueGain",
        label: "Value Gain",
        uniform: "uValueGain",
        type: "float",
        value: 2.2,
        min: 0.2,
        max: 6.0,
        step: 0.05,
        key: { inc: "e", dec: "d", step: 0.1, shiftStep: 0.3 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "zippy-zaps",
    name: "Zippy Zaps",
    description: "Tanh-warped chromatic flow with twistable energy and glow.",
    fragment: zippyZapsFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    params: [
      {
        id: "zoom",
        label: "Zoom",
        uniform: "uZoom",
        type: "float",
        value: 0.2,
        min: 0.05,
        max: 0.5,
        step: 0.005,
        key: { inc: "1", dec: "2", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "timeScale",
        label: "Time Scale",
        uniform: "uTimeScale",
        type: "float",
        value: 1.0,
        min: 0.1,
        max: 3.0,
        step: 0.05,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "twist",
        label: "Twist",
        uniform: "uTwist",
        type: "float",
        value: 1.0,
        min: 0.2,
        max: 2.0,
        step: 0.05,
        key: { inc: "5", dec: "6", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "warp",
        label: "Warp",
        uniform: "uWarp",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 2.0,
        step: 0.05,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "pulse",
        label: "Pulse",
        uniform: "uPulse",
        type: "float",
        value: 1.0,
        min: 0.0,
        max: 2.5,
        step: 0.05,
        key: { inc: "q", dec: "a", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "iterLimit",
        label: "Iter Limit",
        uniform: "uIterLimit",
        type: "float",
        value: 19.0,
        min: 4.0,
        max: 19.0,
        step: 1.0,
        key: { inc: "w", dec: "s", step: 1.0, shiftStep: 3.0 },
      },
      {
        id: "glow",
        label: "Glow",
        uniform: "uGlow",
        type: "float",
        value: 1.0,
        min: 0.4,
        max: 2.0,
        step: 0.05,
        key: { inc: "e", dec: "d", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "colorShift",
        label: "Color Shift",
        uniform: "uColorShift",
        type: "float",
        value: 0.0,
        min: 0.0,
        max: 6.283,
        step: 0.05,
        key: { inc: "r", dec: "f", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "offsetX",
        label: "Offset X",
        uniform: "uOffsetX",
        type: "float",
        value: 0.0,
        min: -0.5,
        max: 0.5,
        step: 0.01,
        key: { inc: "t", dec: "g", step: 0.02, shiftStep: 0.08 },
      },
      {
        id: "offsetY",
        label: "Offset Y",
        uniform: "uOffsetY",
        type: "float",
        value: 0.0,
        min: -0.5,
        max: 0.5,
        step: 0.01,
        key: { inc: "y", dec: "h", step: 0.02, shiftStep: 0.08 },
      },
    ],
  },
  {
    id: "diff-gray-scott",
    name: "Gray-Scott Diffusion",
    description: "Graph-based reaction-diffusion with worms and coral blooms.",
    fragment: diffGrayScottFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    stateful: true,
    bufferSize: 192,
    params: [
      {
        id: "selfWeight",
        label: "Self Weight",
        uniform: "uSelfWeight",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "neighborWeight",
        label: "Neighbor Weight",
        uniform: "uNeighborWeight",
        type: "float",
        value: 1.0,
        min: 0.05,
        max: 2.0,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "du",
        label: "Du",
        uniform: "uDu",
        type: "float",
        value: 0.16,
        min: 0.01,
        max: 0.3,
        step: 0.005,
        key: { inc: "5", dec: "6", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "dv",
        label: "Dv",
        uniform: "uDv",
        type: "float",
        value: 0.08,
        min: 0.01,
        max: 0.3,
        step: 0.005,
        key: { inc: "7", dec: "8", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "feed",
        label: "Feed",
        uniform: "uFeed",
        type: "float",
        value: 0.035,
        min: 0.0,
        max: 0.1,
        step: 0.001,
        key: { inc: "q", dec: "a", step: 0.002, shiftStep: 0.01 },
      },
      {
        id: "kill",
        label: "Kill",
        uniform: "uKill",
        type: "float",
        value: 0.065,
        min: 0.0,
        max: 0.1,
        step: 0.001,
        key: { inc: "w", dec: "s", step: 0.002, shiftStep: 0.01 },
      },
      {
        id: "valueGain",
        label: "Value Gain",
        uniform: "uValueGain",
        type: "float",
        value: 2.4,
        min: 0.2,
        max: 6.0,
        step: 0.05,
        key: { inc: "e", dec: "d", step: 0.1, shiftStep: 0.3 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "diff-edge-flow",
    name: "Edge Flow Vectors",
    description: "Diffusive scalar field rendered as glowing edge-flow vectors.",
    fragment: diffEdgeFlowFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    stateful: true,
    bufferSize: 192,
    params: [
      {
        id: "selfWeight",
        label: "Self Weight",
        uniform: "uSelfWeight",
        type: "float",
        value: 0.6,
        min: 0.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "neighborWeight",
        label: "Neighbor Weight",
        uniform: "uNeighborWeight",
        type: "float",
        value: 1.0,
        min: 0.05,
        max: 2.0,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "decay",
        label: "Decay",
        uniform: "uDecay",
        type: "float",
        value: 0.996,
        min: 0.9,
        max: 0.9999,
        step: 0.0005,
        key: { inc: "5", dec: "6", step: 0.001, shiftStep: 0.005 },
      },
      {
        id: "blobAmp",
        label: "Blob Amp",
        uniform: "uBlobAmp",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 2.0,
        step: 0.02,
        key: { inc: "7", dec: "8", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "blobRadius",
        label: "Blob Radius",
        uniform: "uBlobRadius",
        type: "float",
        value: 0.07,
        min: 0.01,
        max: 0.25,
        step: 0.005,
        key: { inc: "q", dec: "a", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "speed",
        label: "Speed",
        uniform: "uSpeed",
        type: "float",
        value: 0.8,
        min: 0.0,
        max: 3.0,
        step: 0.05,
        key: { inc: "w", dec: "s", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "flowGain",
        label: "Flow Gain",
        uniform: "uFlowGain",
        type: "float",
        value: 3.0,
        min: 0.2,
        max: 8.0,
        step: 0.1,
        key: { inc: "e", dec: "d", step: 0.2, shiftStep: 0.6 },
      },
      {
        id: "flowThreshold",
        label: "Flow Threshold",
        uniform: "uFlowThreshold",
        type: "float",
        value: 0.02,
        min: 0.0,
        max: 0.2,
        step: 0.005,
        key: { inc: "r", dec: "f", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
  {
    id: "diff-threshold",
    name: "Threshold Feedback",
    description: "Diffusion with nonlinear feedback for digital fungus crackle.",
    fragment: diffThresholdFrag,
    resolutionUniform: "uResolution",
    timeUniform: "uTime",
    timeMode: "seconds",
    stateful: true,
    bufferSize: 192,
    params: [
      {
        id: "selfWeight",
        label: "Self Weight",
        uniform: "uSelfWeight",
        type: "float",
        value: 0.5,
        min: 0.0,
        max: 2.0,
        step: 0.01,
        key: { inc: "1", dec: "2", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "neighborWeight",
        label: "Neighbor Weight",
        uniform: "uNeighborWeight",
        type: "float",
        value: 1.0,
        min: 0.05,
        max: 2.0,
        step: 0.01,
        key: { inc: "3", dec: "4", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "decay",
        label: "Decay",
        uniform: "uDecay",
        type: "float",
        value: 0.995,
        min: 0.9,
        max: 0.9999,
        step: 0.0005,
        key: { inc: "5", dec: "6", step: 0.001, shiftStep: 0.005 },
      },
      {
        id: "threshold",
        label: "Threshold",
        uniform: "uThreshold",
        type: "float",
        value: 0.5,
        min: 0.1,
        max: 0.9,
        step: 0.01,
        key: { inc: "7", dec: "8", step: 0.02, shiftStep: 0.06 },
      },
      {
        id: "sharpness",
        label: "Sharpness",
        uniform: "uSharpness",
        type: "float",
        value: 18.0,
        min: 1.0,
        max: 40.0,
        step: 0.5,
        key: { inc: "q", dec: "a", step: 1.0, shiftStep: 4.0 },
      },
      {
        id: "noiseAmp",
        label: "Noise Amp",
        uniform: "uNoiseAmp",
        type: "float",
        value: 0.08,
        min: 0.0,
        max: 0.5,
        step: 0.01,
        key: { inc: "w", dec: "s", step: 0.02, shiftStep: 0.06 },
      },
      {
        id: "injectAmp",
        label: "Inject Amp",
        uniform: "uInjectAmp",
        type: "float",
        value: 0.2,
        min: 0.0,
        max: 1.5,
        step: 0.02,
        key: { inc: "e", dec: "d", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "injectRadius",
        label: "Inject Radius",
        uniform: "uInjectRadius",
        type: "float",
        value: 0.06,
        min: 0.01,
        max: 0.25,
        step: 0.005,
        key: { inc: "r", dec: "f", step: 0.01, shiftStep: 0.03 },
      },
      {
        id: "speed",
        label: "Speed",
        uniform: "uSpeed",
        type: "float",
        value: 0.9,
        min: 0.0,
        max: 3.0,
        step: 0.05,
        key: { inc: "t", dec: "g", step: 0.05, shiftStep: 0.2 },
      },
      {
        id: "seed",
        label: "Seed",
        uniform: "uSeed",
        type: "seed",
        value: 0,
      },
    ],
  },
];




